config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :planets, except: [:edit, :update] do
    resources :bookings, only: [:new, :create]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :planet
end

app/models/planet.rb
class Planet < ApplicationRecord

  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  # validates :image_url, presence: true
  # validates :price, presence: true
  # validates :rating, numericality: { only_integer: true }
  # validates :rating, inclusion: { in: 0..5 }
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :planets
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.planet = Planet.find(params[:planet_id])
    @booking.save
    if @booking.save
      redirect_to planet_path(@booking.planet)
    else
      render :new
    end
  end
end

private

def booking_params
  params.require(:booking).permit(:date_start, :date_end, :planet_id, :comment)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  def index
    if params[:query].present?
      @planets = Planet.search_by_name_and_description(params[:query]).order(created_at: :asc)
    else
      @planets = Planet.all.order(created_at: :asc)
    end
  end

  def show
    @planet = Planet.find(params[:id])
  end

  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.new(planet_params)
    @planet.user = current_user
    if @planet.save
      redirect_to planets_path, notice: "Added #{@planet.name}!"
    else
      render :new
    end
  end

  def destroy
    @planet = Planet.find(params[:id])
    @planet.destroy
    redirect_to planets_path
  end

  private

  def planet_params
    params.require(:planet).permit(:name, :description, :image_url, :population, :rating, :price, :size, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="new-booking form-container">
  <div class="logo-title-container">
  <h1>Create Booking</h1>
    <div class="icon-container">
      <%= image_tag "logo-blue.png", alt: "Logo" %>
    </div>
  </div>

  <%= simple_form_for(@booking, url: planet_bookings_path) do |f| %>
    <%= f.input :date_start, as: :date, html5: true  %>
    <%= f.input :date_end, as: :date, html5: true %>
    <%= f.input :comment %>
      <div class="form-actions btn-container">
        <%= f.button :submit, "create booking", class: "button-primary" %>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>No-Airbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('logo-blue.png') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <!--div class="alert"><%= notice %></div>
  <p class="alert"><%= alert %></p> -->
    <%= yield %>

    <div class="navbar-lewagon">
      <%= link_to "/" do %>
        <i class="fa-2x fa-solid fa-house"></i>
      <% end %>
      <%= link_to "/planets" do %>
        <i class="fa-2x fa-solid fa-earth-americas"></i>
      <% end %>
      <%= link_to "/planets/new" do %>
        <i class="fa-2x fa-solid fa-square-plus"></i>
      <% end %>
      <%= link_to "/users/edit" do %>
        <i class="fa-2x fa-solid fa-user"></i>
      <% end %>
    </div>
  </body>
</html>

<script>
  function hideLoadingDiv() {
    setTimeout(function(){
      document.getElementById('add-planet').classList.add('notice-hidden');
    },1000)
  }
</script>

app/views/pages/home.html.erb
<div class="main-container">
  <div class="logo-container">
    <%= image_tag "logo-white.png", alt: "Logo" %>
    <h1><span style="color: #6700c7">No</span>AirBnB</h1>
    <h2>Planetary vacations for the<br>discerning galactic overlord</h2>
  </div>
  <div class="btn-container">
    <%= link_to "Explore planets", "/planets", class: "button-primary" %>
    <%= link_to "No-AirBnB your Planet", "/planets/new" %>
  </div>
</div>

app/views/planets/index.html.erb
<div class="index-container">
  <div class="index-search">
  <%= form_with url: planets_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "  Find a planet"
    %>
    <%= button_tag(type: "submit", class: "btn btn-primary") do %>
      <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
  </div>
  <%# <h1>Planets </h1> %>
  <ul>
    <% @planets.each do |planet| %>
      <%= link_to planet_path(planet) do %>
      <li class="index-card">
        <%= cl_image_tag planet.photo.key, alt: "planet-image", class: "card-img" %>
        <div class="card-info">
          <h2><%= planet.name %></h2>
          <div class="justify-container">
            <p><%="⭐" * planet.rating %></p>
            <h4>£ <%= planet.price %></h4>
          </div>
          <p><%= planet.description %></p>
        </div>
      </li>
      <% end %>


    <% end %>
  </ul>
</div>

app/views/planets/new.html.erb
<div class="new-planet form-container">
  <div class="logo-title-container">
  <h1>New Planet</h1>
    <div class="icon-container">
      <%= image_tag "logo-blue.png", alt: "Logo" %>
    </div>
  </div>
  <%= simple_form_for(@planet) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :size %>
    <%= f.input :population %>
    <%= f.input :photo, as: :file %>
    <%= f.input :rating, collection: 1..5 %>
    <div class="form-actions btn-container">
      <%= f.button :submit, "Create Planet", class: "button-primary" %>
    </div>
  <% end %>

</div>

app/views/planets/show.html.erb
<div>
  <div class="container-top-btn">
        <div>
    <%= link_to "/planets" do %>
        <i class="fa-solid fa-chevron-left button-round"></i>
      <% end %></div>
  </div>
  <%= cl_image_tag @planet.photo.key, alt: "planet-image", class: "card-img" %>
</div>

<div class="info-container">
  <div class="title-container">
    <h1> <%= @planet.name %></h1>
  </div>
  <div class="rating-price-container">
    <h3><%="⭐" * @planet.rating %></h3>
    <p>£ <%= @planet.price %></p>
  </div>
</div>




<div class="container-offers">
  <div>
    <hr>
      <p><%= @planet.description%></p>
    <hr>
  </div>
  <div class = "title">
    <h3>What this planet offers</h3>
  </div>
<div class="icons">
  <div class = "pop">
    <i class="fa-solid fa-people-group"></i>
    <p><%= @planet.population %> people</p>
  </div>
  <div class = "size">
      <i class="fa-solid fa-ruler-horizontal"></i>
      <p><%= @planet.size %> km/diameter</p>
  </div>
</div>
<hr>
<div class = "container-price">
  <div class="title">
    <h3>Price per night</h3>
  </div>
  <p>£ <%= @planet.price %></p>
</div>

  <div class="booking-container">
    <h2>Your Bookings</h2>
   <hr>
    <div >
      <% @planet.bookings.each do |booking|%>

        <p class="booking-list-container">-  <%= booking.date_start.strftime("%b %d") %>  -  <%= booking.date_end.strftime("%b %d") %>  :  <span style="color: #bbbbbb"><%= booking.comment %></span></p>
      <% end%>
    </div>
   <hr>
  </div>

  <br>

  <div class="btn-container">
    <%= link_to "Book now", new_planet_booking_path(@planet), class: "button-primary" %>
  </div>

  <div class="btn-container">
    <%= link_to "Delete Planet", planet_path(@planet), data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?'}, class: "button-delete" %>
  </div>
</div>

</div>